language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      script:
        - export CC=gcc-8
        - export CXX=g++-8
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --config Release --target install
        - cd ..
        - ./bin/jigsaw example.jig
        - cd uni
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - ./test_1
        - ./test_2
        - ./test_3
        - ./test_4
        - ./test_5
        - ./test_6
        - ./test_7
        - ./test_8
        - ./test_9
         
    - os: osx
      osx_image: xcode11
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --config Release --target install
        - cd ..
        - ./bin/jigsaw example.jig
        - cd uni
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - ./test_1
        - ./test_2
        - ./test_3
        - ./test_4
        - ./test_5
        - ./test_6
        - ./test_7
        - ./test_8
        - ./test_9
      
    - os: windows
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --config Release --target install
        - cd ..
        - ls
        - ./bin/jigsaw.exe example.jig
        - copy ./lib/jigsaw.dll ./uni
        - cd uni
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - ./test_1.exe
        - ./test_2.exe
        - ./test_3.exe
        - ./test_4.exe
        - ./test_5.exe
        - ./test_6.exe
        - ./test_7.exe
        - ./test_8.exe
        - ./test_9.exe
