language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      script:
        - export CC=gcc-8
        - export CXX=g++-8
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - rm -r build
        - cd uni
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - rm -r build
        - ./test2d_a
        - ./test3d_a
        - ./test2s_a
        - ./test2d_b
        - ./test3d_b
        - ./test2s_b
        - ./test2d_c
        - ./test3d_c
        - ./test2s_c
        - ./test2d_d
        - ./test3d_d
        - ./test2d_e
        - ./test3d_e
        - ./test2s_e
        - ./test2d_f
        - ./test3d_f
        - ./test2s_f
        - ./test2d_g
        - ./test3d_g
        - ./test2s_g
        - ./test2d_h
        - ./test2s_h
        - ./test2d_i
        - ./test2s_i
        - cd ..
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --config Release --target install
        - cd ..
        - rm -r build
        - ./bin/jigsaw example.jig
        - ./bin/jigsaw geo/airfoil.jig
        - ./bin/jigsaw geo/bunny.jig
        - ./bin/jigsaw geo/parts.jig
        - ./bin/jigsaw geo/earth.jig
        - ./bin/jigsaw geo/lakes.jig
        
    - os: osx
      osx_image: xcode11
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - rm -r build
        - cd uni
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - rm -r build
        - ./test2d_a
        - ./test3d_a
        - ./test2s_a
        - ./test2d_b
        - ./test3d_b
        - ./test2s_b
        - ./test2d_c
        - ./test3d_c
        - ./test2s_c
        - ./test2d_d
        - ./test3d_d
        - ./test2d_e
        - ./test3d_e
        - ./test2s_e
        - ./test2d_f
        - ./test3d_f
        - ./test2s_f
        - ./test2d_g
        - ./test3d_g
        - ./test2s_g
        - ./test2d_h
        - ./test2s_h
        - ./test2d_i
        - ./test2s_i
        - cd ..
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --config Release --target install
        - cd ..
        - rm -r build
        - ./bin/jigsaw example.jig
        - ./bin/jigsaw geo/airfoil.jig
        - ./bin/jigsaw geo/bunny.jig
        - ./bin/jigsaw geo/parts.jig
        - ./bin/jigsaw geo/earth.jig
        - ./bin/jigsaw geo/lakes.jig
      
    - os: windows
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - rm -r build
        - cp lib/jigsaw.dll uni
        - cd uni
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug --target install
        - cd ..
        - rm -r build
        - ./test2d_a
        - ./test3d_a
        - ./test2s_a
        - ./test2d_b
        - ./test3d_b
        - ./test2s_b
        - ./test2d_c
        - ./test3d_c
        - ./test2s_c
        - ./test2d_d
        - ./test3d_d
        - ./test2d_e
        - ./test3d_e
        - ./test2s_e
        - ./test2d_f
        - ./test3d_f
        - ./test2s_f
        - ./test2d_g
        - ./test3d_g
        - ./test2s_g
        - ./test2d_h
        - ./test2s_h
        - ./test2d_i
        - ./test2s_i
        - cd ..
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --config Release --target install
        - cd ..
        - rm -r build
        - ./bin/jigsaw example.jig
        - ./bin/jigsaw geo/airfoil.jig
        - ./bin/jigsaw geo/bunny.jig
        - ./bin/jigsaw geo/parts.jig
        - ./bin/jigsaw geo/earth.jig
        - ./bin/jigsaw geo/lakes.jig
